const { buildSchema } = require('graphql');

module.exports = buildSchema(`
  """
  A MovieType contains persisted attributes for a Movie
  """
  type MovieType {
    "Movie ID generated by MongoDB"
    _id: ID!
    "Title of a movie"
    title: String!
    "Released year"
    year: String!
    "Released date"
    released: String!
    "Small plot about the storyline"
    plot: String!
    "Added by this user"
    creator: UserType!
    "Link to movie poster"
    poster: String!
    "Duration of the movie"
    duration: String!
    "Director of the movie"
    director: String!
    "Main actors of the movie"
    actors: String!
    "Country of the movie"
    country: String!
    "Type of media"
    type: String!
    "Production society"
    production: String!
  }

  """
  A UserType contains persisted attributes for a User
  """
  type UserType {
    "User ID generated by MongoDB"
    _id: ID!
    "Pseudo of the user"
    pseudo: String!
    "Email of the user"
    email: String!
    "Encrypted password"
    password: String
    "User references for all movies he has been created"
    createdMovies: [MovieType!]!
    "Count of movies that has been created by user"
    numberOfCreatedMovies: String
  }

  """
  AuthDataType contains authentication attributes
  """
  type AuthDataType {
    userId: ID!
    token: String!
    tokenExpiration: Int!
  }

  input MovieInput {
    title: String!
    year: String!
    released: String!
    plot: String!
    poster: String!
    duration: String!
    director: String!
    actors: String!
    country: String!
    type: String!
    production: String!
  }

  input UserInput {
    pseudo: String!
    email: String!
    password: String!
  }

  type RootQuery {
    movies: [MovieType!]!
    movie(movieId: String!): MovieType
    users: [UserType!]!
    user(userId: String!): UserType
    login(email: String!, password: String!): AuthDataType
  }

  type RootMutation {
    createMovie(movieInput: MovieInput): MovieType
    createUser(userInput: UserInput): UserType
    deleteMovie(movieId: String!): MovieType
  }

  schema {
    query: RootQuery
    mutation: RootMutation
  }
`);
